add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/object/msgpack_object.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/pipework/pipework_components.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/pipework/reducer.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/object/msgpack_object_code_reducer.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/object/msgpack_object_components.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/object/msgpack_structure_stack.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/pipework/chopper.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/kvmap/msgpack_kvmap_components.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/kvmap/msgpack_kvmap_key_match_aggregator.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/object/msgpack_object_code_compare.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/object/msgpack_object_code_fifo.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/object/msgpack_object_encode_string_constant.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/object/msgpack_object_match_aggregator.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/object/msgpack_object_packer.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/object/msgpack_object_unpacker.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/pipework/queue_arbiter.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/rpc/msgpack_rpc.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/kvmap/msgpack_kvmap_key_compare.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/rpc/msgpack_rpc_components.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/rpc/msgpack_rpc_server_requester.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/rpc/msgpack_rpc_server_responder.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/object/msgpack_object_encode_array.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/rpc/msgpack_rpc_method_main_no_param.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/rpc/msgpack_rpc_method_return_code.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/rpc/msgpack_rpc_server.vhd
add_vhdl_file sources_1 WORK ../../src/main/vhdl/tinymt32.vhd
add_vhdl_file sources_1 WORK ../../src/main/vhdl/zundoko_interface.vhd
add_vhdl_file sources_1 WORK ../../src/main/vhdl/zundoko_main.vhd
add_vhdl_file sources_1 WORK ../../src/main/vhdl/zundoko_server.vhd
