qip: msgpack_altera.qip pipework_altera.qip

msgpack_altera.qip  : msgpack_altera.yml
	../../../../../../PipeWork/tools/vhdl-archiver.rb -v --config $<

pipework_altera.qip : pipework_altera.yml
	../../../../../../PipeWork/tools/vhdl-archiver.rb -v --config $<

