add_vhdl_file sim_1     DUMMY_PLUG ../../../../Dummy_Plug/src/main/vhdl/core/util.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../../Dummy_Plug/src/main/vhdl/core/reader.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../../Dummy_Plug/src/main/vhdl/core/sync.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../../Dummy_Plug/src/main/vhdl/core/vocal.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../../Dummy_Plug/src/main/vhdl/axi4/axi4_types.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../../Dummy_Plug/src/main/vhdl/core/core.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../../Dummy_Plug/src/main/vhdl/axi4/axi4_core.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../../Dummy_Plug/src/main/vhdl/axi4/axi4_stream_player.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../../Dummy_Plug/src/main/vhdl/axi4/axi4_models.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../../Dummy_Plug/src/main/vhdl/axi4/axi4_stream_master_player.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../../Dummy_Plug/src/main/vhdl/axi4/axi4_stream_slave_player.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../../Dummy_Plug/src/main/vhdl/core/marchal.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/object/msgpack_object.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/pipework/pipework_components.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/pipework/reducer.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/object/msgpack_object_code_compare.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/object/msgpack_object_code_reducer.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/object/msgpack_object_components.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/object/msgpack_structure_stack.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/pipework/chopper.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/pipework/queue_register.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/kvmap/msgpack_kvmap_components.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/kvmap/msgpack_kvmap_key_compare.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/kvmap/msgpack_kvmap_key_match_aggregator.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/object/msgpack_object_code_fifo.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/object/msgpack_object_decode_integer.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/object/msgpack_object_encode_string_constant.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/object/msgpack_object_match_aggregator.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/object/msgpack_object_packer.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/object/msgpack_object_unpacker.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/pipework/queue_arbiter.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/rpc/msgpack_rpc.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/rpc/msgpack_rpc_components.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/rpc/msgpack_rpc_method_main_with_param.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/rpc/msgpack_rpc_method_return_integer.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/rpc/msgpack_rpc_method_set_param_integer.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/rpc/msgpack_rpc_server_requester.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/rpc/msgpack_rpc_server_responder.vhd
add_vhdl_file sources_1 MSGPACK ../../../../msgpack-vhdl/src/msgpack/rpc/msgpack_rpc_server.vhd
add_vhdl_file sources_1 MSGPACK ../../src/main/synthesijer/ADD.vhd
add_vhdl_file sources_1 MSGPACK ../../src/main/vhdl/add_interface.vhd
add_vhdl_file sources_1 MSGPACK ../../src/main/vhdl/add_server.vhd
add_vhdl_file sim_1     WORK ../../src/test/vhdl/test_bench.vhd
